### ISSUE TITLE
Add some redux

### ISSUE THREAD

**Issue by da1nerd** [neutrinog/react-app-electron-template#6]

**Comment by yoDon** [comment]
For those of us just looking for how to combine create react app with electron, it's actually much nicer to have this in it's current minimalist form. Some visitors might want to use it with redux but others are as likely to prefer mobx or react hooks or etc. Given that it's based on create react app it's trivial to find examples of how to add any of those state patterns. What's hard is disassembling someone's complex template to figure out which of the npm packages you don't want is actually required by the implementation and which are just there because the original dev liked them.

**Comment by da1nerd** [comment]
That's a good point @yoDon. In the yeoman generator form of this template (see https://github.com/neutrinog/generator-react-app-electron) I've been playing around with some more specialized configuration like redux and other features. Maybe what I'll do is use this minimalist template as the baseline and include some optional configurations to the generator so people don't get forced into a corner.

**Comment by da1nerd** [comment]
This repo now serves as the template in https://github.com/neutrinog/generator-react-app-electron (as a submodule).
So any improvements to this template will eventually find it's way into that yeoman generator.
